StockVinul/stockproject/Pages/Stock/Admin/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.ExternalModels;

namespace stockproject.Pages.Admin
{
    public class AdminModel : PageModel
    {
        /*
         * หน้า admin หน้านี้มีไว้ดูสรุปว่ามีบิลกี่บิลในระบบ ณ ปัจจุบัน
         * คำสั่งนี้มีไว้ขอใช้ Database โดยจะใช้ผ่านตัวแปรที่ชื่อว่า db
         */

        private readonly StockprojectContext db = new StockprojectContext();

        //คุณสมบัติ BindProperty ทำให้ตัวแปรที่อยู่ภายใต้อันนี้ (แค่1ตัว) สามารถรับค่าผ่านไปมาระหว่างหน้าเว็ปและหน้าที่เขียนโค้ดได้
        [BindProperty]
        public List<QueryAdmin_FormIn> listFromIn { get; set; } = new List<QueryAdmin_FormIn>();

        [BindProperty]
        public List<QueryAdmin_FormOut> listFormOut { get; set; } = new List<QueryAdmin_FormOut>();
        public List<string> id { get; set; }

        [BindProperty]
        public int totalIn { get; set; }
        [BindProperty]
        public int confirmedIn { get; set; }
        [BindProperty]
        public int rejectedIn { get; set; }
        [BindProperty]
        public int waittingIn { get; set; }

        [BindProperty]
        public int totalOut { get; set; }
        [BindProperty]
        public int confirmedOut { get; set; }
        [BindProperty]
        public int rejectedOut { get; set; }
        [BindProperty]
        public int waittingOut { get; set; }

        //ฟังชั่น onget จะเรียกทุกครั้งที่มีการเข้าถึงหน้านี้ เช่น การโหลดหน้าเว็ปหน้านี้ หรือเข้า Url นี้โดย OnGet ต้องเขียนแบบนี้เท่านั้น และตามด้วยชื่อฟังชั่น แต่ถ้าไม่มีมันจะคือ Default
        public void OnGet()
        {

            /*
             * ประกาศตัวแปร q2ให้มารับค่าจากดาต้าเบสในตาราง formin
             * var คือการไม่กำหนด Type คอมไพล์เลอร์จะหา Type ที่เหมาะสมให้ตัวแปรนั้นเอง
             * from t1 in db.FormIn คือ ตั้งตัวแปรชื่อว่า t1 เอาค่าในดาต้าเบส -> ตาราง FormIn
             * select new  เลือกใหม่ เลือกคอลัม FormInid,Status,Createdate
             * { t1.FormInid, t1.Status, t1.Createdate })*/

            var q2 = (from t1 in db.FormIn
                      select new { t1.FormInid, t1.Status, t1.Createdate });

            //วนลูป q2 โดย foreach จะวนลูปถึงตัวสุดท้ายโดนอัตโนมัติ
            foreach (var item in q2)
            {
                //สร้างตัวแปร QueryFormIn มี Type เป็นQueryAdmin_FormIn มาเพื่อกำหนดค่าลงในตัวแปรเพื่อนำไปใช้ต่อ

                QueryAdmin_FormIn QueryFormIn = new QueryAdmin_FormIn();

                QueryFormIn.id = item.FormInid; /*กำหนดค่า QueryFormIn.id = ค่าทางด้านขวาที่เอามาจากดาต้าเบส*/
                QueryFormIn.Subject = "FormIn";
                QueryFormIn.Createdate = item.Createdate;
                QueryFormIn.Status = item.Status;
                listFromIn.Add(QueryFormIn); /*เพิ่มค่าลงตัวแปร listFromIn โดยใช้คำสั่ง Add(ค่าที่ต้องการจะใส่เข้าไป)*/

                //เมื่อทำแบบนี้จนหมดตัวแปร listFromIn จะมีขนาดเท่ากับ q2 หรือคือค่าที่นำมาจากดาต้าเบส แต่ค่าใน listFromInจะเพิ่มเติมคำว่า FormIn เพื่อแยกว่านี่คือการนำเข้าหรือออก
            }

            //q3 ทำเหมือน q2 แตกต่างที่นี่คือ FormOut
            var q3 = (from t1 in db.FormOut
                      select new { t1.FormOutid, t1.Status, t1.Createdate });


            foreach (var item in q3)
            {
                QueryAdmin_FormOut QueryFormOut = new QueryAdmin_FormOut();
                QueryFormOut.id = item.FormOutid;
                QueryFormOut.Subject = "FormOut";
                QueryFormOut.Createdate = item.Createdate;
                QueryFormOut.Status = item.Status;
                listFormOut.Add(QueryFormOut);
            }
            summayReport();
        }

        /*
         * OnPost คือคำสั่งการกำหนด methord ให้ทำงานแบบ post หรือคือการส่งค่าผ่าน <from></from>
         * โดย OnPost ต้องเขียนแบบนี้เท่านั้นและตามด้วยชื่อฟังชั่น โดยทำผ่าน action ที่เรียกว่า ActionResult เท่านั้น
         */

        //ฟังชั่นนี้ไว้สำหรับการรับค่าและส่งไปให้หน้า confirmstatus โดยมี Parmmeter 2 ตัวคือ id ของ form และชนิดของ formt หรือtype
        public ActionResult OnPostVALUE(int id, string type)
        {
            /*คำสั่งส่งค่าข้ามหน้า ต้องทำผ่าน action ActionResult เท่านั้น  
             * โดย "./confirmstatus" คือการสั่งให้ไปที่หน้านี้ . (จุด) คือหมายถึงลำดับชั้นไฟล์เดียวกัน หรือคือให้ออกจากหน้านี้ไปต้องออกจากโฟล์เดอร์นี้
             * .. (จุดจุด) หมายถึงให้ออกจากโฟล์เดอรืนี้ 
             * "OnGet" คือการสั่งให้ไปที่ฟังชั่นนี้ 
             * new { formid = id, formtype = type } สั่งให้ส่ง Parmeter 2ตัวคือ id,type
             
             */
            return RedirectToPage("./confirmstatus", "OnGet", new { formid = id, formtype = type });
        }

        //ฟังชีั่น GoToCreateForm หน้าที่คือถ้ากดปุ่มนี้จะเปี่ลยหน้าไปที่ Product
        public ActionResult OnPostGoToCreateForm()
        {
            return RedirectToPage("/Stock/Product");
        }

       public void summayReport()
        {
            var inList = (from t1 in db.FormIn select t1);
            totalIn = inList.Count();
            confirmedIn = inList.Where(c => c.Status == "confirm" && c.Isstatus == true).Count();
            rejectedIn = inList.Where(c => c.Status == "reject" && c.Isstatus == true).Count();
            waittingIn = inList.Where(c => c.Status == "wait" && c.Isstatus == false).Count();
            var outList = (from t1 in db.FormOut select t1);
            totalOut = outList.Count();
            confirmedOut = outList.Where(c => c.Status == "confirm" && c.Isstatus == true).Count();
            rejectedOut = outList.Where(c => c.Status == "reject" && c.Isstatus == true).Count();
            waittingOut = outList.Where(c => c.Status == "wait" && c.Isstatus == false).Count();
        }

    }
}

StockVinul/stockproject/Pages/Stock/Admin/CreateUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using stockproject.Enititys;

namespace stockproject
{
    public class CreateUserModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();

        public void OnGet()
        {
            roledb = (from t1 in db.Role
                      select new SelectListItem
                      {
                          Value = t1.Roleid.ToString(),
                          Text = t1.Rolename
                      }).ToList();
        }
        public ActionResult OnPostToCreate()
        {
           
            User user = new User();
            user.Username = userinput.Username;
            user.Password = userinput.Password;
            user.FullName = userinput.FullName;
            user.Phone = userinput.Phone;
            user.Contact = userinput.Contact;
            user.Roleid = Convert.ToInt32(roleid);

            db.User.Add(user);
            db.SaveChanges();

            return RedirectToPage("./Admin", "OnGet");
        }



        [BindProperty]
        public string roleid { get; set; }
        [BindProperty]
        public User userinput { get; set; } = new User();
        public List<SelectListItem> roledb { get; set; } = new List<SelectListItem>();

    }
}

StockVinul/stockproject/Pages/Stock/Admin/confirmstatus.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.ExternalModels;

namespace stockproject
{

    public class confirmstatusModel : PageModel
    {
        /*
    * หน้า confirmstatus มีไว้ให้ admin ดูรายละเอียดของบิลและ confrim หรือ reject ที่หน้านี้
   
    */
        private StockprojectContext db = new StockprojectContext();

        [BindProperty]
        public List<AdminConfirm> list { get; set; } = new List<AdminConfirm>();
        [BindProperty]
        public List<DetailForm> listtest { get; set; } = new List<DetailForm>();
        public List<ProductFormIn> temp { get; set; } = new List<ProductFormIn>();
        public List<ProductFormOut> temp2 { get; set; } = new List<ProductFormOut>();

        [BindProperty]
        public ResultForm formHeader { get; set; }
        [BindProperty]
        public List<DetailForm> formDetail { get; set; } = new List<DetailForm>();
        public string typeInText { get; set; } = "รายการนำสินค้าเข้า";
        public string typeOutText { get; set; } = "รายการจ่ายสินค้าออก";

        //ฟังชั่น OnGet รับค่ามาจากหน้า Admin ที่กดปุ่มVALUE
        public ActionResult OnGet(int formid, string formtype,string err = null)
        {
            list.Clear();
            listtest.Clear();
            temp.Clear();
            temp2.Clear();
            formDetail.Clear();
            if (formtype == "รายการนำสินค้าเข้า")
            {
                formtype = "FormIn";
            }
            else if (formtype == "รายการจ่ายสินค้าออก")
            {
                formtype = "FormOut";
            }

            if (err != null)
            {
                ModelState.AddModelError(string.Empty, "" + err + " ของใน Stock มีไม่พอ");
            }
            //คำสั่งรับค่าจากระบบที่ทำการ login ที่ระบบว่าคนนี้คือใคร ในที่นี้เอาค่าที่อยู่ในตัวแปร NameIdentifier ออกมาเป็นไว้ในตัวแปร userid และแปลงค่าเป็น int
            var userid = Convert.ToInt32(User.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault());
            ViewData["confirm"] = "Yes";
            if (formtype == "FormIn")
            {
                formHeader = db.FormIn.Select(a => new ResultForm()
                {
                    Formid = a.FormInid,
                    IsIn = false,
                    Status = a.Status,
                    Createdate = a.Createdate,
                    Statusdate = a.Statusdate,
                    Userid = a.Userid

                }).Single(a => a.Formid == formid);
                ViewData["id"] = formid;
                ViewData["type"] = typeInText;
                var q2 = from a in db.ProductFormIn
                         join b in db.FormIn on a.FormInid equals b.FormInid
                         join c in db.User on b.Userid equals c.Userid
                         join d in db.Product on a.ProductId equals d.Productid
                         where (b.FormInid == formid)
                         select new { c.FullName, b.Createdate, b.Isstatus, d.Productname, a.Qty, a.Price, a.ProductId, d.Picpath };
                foreach (var item in q2)
                {
                    if (item.Isstatus == true)
                    {
                        ViewData["status"] = "True";
                    }
                    else
                    {
                        ViewData["status"] = "False";
                    }

                    ViewData["date"] = item.Createdate;
                    ViewData["name"] = item.FullName;

                    AdminConfirm confirm = new AdminConfirm();
                    confirm.product = item.Productname;
                    confirm.qty = item.Qty;
                    confirm.price = item.Price;
                    confirm.productid = item.ProductId;
                    confirm.Picpath = item.Picpath;
                    list.Add(confirm);


                    //list.Add(new AdminConfirm
                    //{
                    //    product = item.Productname,
                    //    qty = item.Qty,
                    //    // Createdate = item.Createdate,
                    //    price = item.Price,
                    //    productid= item.ProductId
                    //    //name= item.Username
                    //});
                }
            }

            else
            {

                formHeader = db.FormOut.Select(a => new ResultForm()
                {
                    Formid = a.FormOutid,
                    IsIn = false,
                    Status = a.Status,
                    Createdate = a.Createdate,
                    Statusdate = a.Statusdate,
                    Userid = a.Userid
                }).Single(a => a.Formid == formid);
                ViewData["id"] = formid;
                ViewData["type"] = typeOutText;
                var q2 = from a in db.ProductFormOut
                         join b in db.FormOut on a.FormOutid equals b.FormOutid
                         join c in db.User on b.Userid equals c.Userid
                         join d in db.Product on a.ProductId equals d.Productid
                         where (b.FormOutid == formid)
                         select new { c.FullName, b.Createdate, b.Isstatus, d.Productname, a.Qty, a.Price, a.ProductId, d.Picpath };

                foreach (var item in q2)
                {
                    if (item.Isstatus == true)
                    {
                        ViewData["status"] = "True";
                    }
                    else
                    {
                        ViewData["status"] = "False";
                    }
                    ViewData["date"] = item.Createdate;
                    ViewData["name"] = item.FullName;

                    AdminConfirm confirm = new AdminConfirm();
                    confirm.product = item.Productname;
                    confirm.qty = item.Qty;
                    confirm.price = item.Price;
                    confirm.productid = item.ProductId;
                    confirm.Picpath = item.Picpath;
                    list.Add(confirm);

                    //list.Add(new AdminConfirm
                    //{
                    //    product = item.Productname,
                    //    qty = item.Qty,
                    //    // Createdate = item.Createdate,
                    //    price = item.Price,
                    //    //name= item.Username
                    //    productid=item.ProductId
                    //});
                }


                for (int i = 0; i < list.Count; i++)
                {

                    var q3 = from a in db.Product
                             where (a.Productid == list[i].productid)
                             select a;

                    foreach (var item2 in q3)
                    {

                        if (list[i].qty > item2.Qty)
                        {
                            ModelState.AddModelError(string.Empty, "'" + item2.Productname + "' ของใน Stock มีไม่พอ ให่ยืนยันได้");
                            ViewData["confirm"] = "No";
                        }
                    }
                }

            }
            return Page();
        }

        public ActionResult OnPostCONFIRM(string id, string type)
        {
            if (type == typeInText)
            {
                var q = (from a in db.ProductFormIn
                        where (a.FormInid == Int32.Parse(id))
                        select new { a.ProductId, a.Qty }).ToList();

                foreach (var item in q)
                {
                    ProductFormIn formin = new ProductFormIn();
                    formin.ProductId = item.ProductId;
                    formin.Qty = item.Qty;
                    temp.Add(formin);
                    //temp.Add(new ProductFormIn
                    //{
                    //    ProductId = item.ProductId,
                    //    Qty = item.Qty,

                    //});

                }

                for (int i = 0; i < temp.Count; i++)
                {

                    var q2 = from a in db.Product
                             where (a.Productid == temp[i].ProductId)
                             select a;

                    foreach (Product item2 in q2)
                    {
                        item2.Qty = item2.Qty + temp[i].Qty;
                        item2.Modifydate = DateTime.Now;
                    }
                }

                var q3 = from c in db.FormIn
                         where c.FormInid == Int32.Parse(id)
                         select c;
                foreach (FormIn c in q3)
                {
                    c.Isstatus = true;
                    c.Status = "confirm";
                    c.Statusdate = DateTime.Now;
                }
                db.SaveChanges();

            }
            else if (type == typeOutText)
            {
                var q = from a in db.ProductFormOut
                        where (a.FormOutid == Int32.Parse(id))
                        select new { a.ProductId, a.Qty };

                foreach (var item in q)
                {
                    ProductFormOut formout = new ProductFormOut();
                    formout.ProductId = item.ProductId;
                    formout.Qty = item.Qty;
                    temp2.Add(formout);
                    //temp2.Add(new ProductFormOut
                    //{
                    //    ProductId = item.ProductId,
                    //    Qty = item.Qty,

                    //});

                }

                for (int i = 0; i < temp2.Count; i++)
                {

                    var q2 = from a in db.Product
                             where (a.Productid == temp2[i].ProductId)
                             select a;

StockVinul/stockproject/Pages/Stock/Admin/CreateUser.cshtml
@page
@model stockproject.CreateUserModel
@{
    ViewData["Title"] = "CreateUser";
    Layout = "~/Pages/Shared/_Layoutadmin.cshtml";
}

<form method="post" enctype="multipart/form-data">
    <div class="row mt-5 mb-3">
        <div class="col-12 text-center">
            <h3>เพิ่มผู้ใช้</h3>
        </div>
    </div>
    <div class="container-create-product">
        <div class="wrap-create-product">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label for="formGroupExampleInput">ชื่อผู้ใช้</label>
                        @Html.TextBoxFor(m=>m.userinput.Username , new {@class="form-control my-text-input-custom",@type="text",@placeholder="Username",@required="required" })
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput1">รหัสผ่าน</label>
                        @Html.TextBoxFor(m => m.userinput.Password, new { @class = "form-control my-text-input-custom", @type = "text", @placeholder = "Password", @required = "required" })
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput2">ชื่อ - นามสกุล</label>
                        @Html.TextBoxFor(m => m.userinput.FullName, new { @class = "form-control my-text-input-custom", @type = "text", @placeholder = "ชื่อเต็ม", @required = "required" })
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput3">โทร</label>
                        @Html.TextBoxFor(m => m.userinput.Phone, new { @class = "form-control my-text-input-custom", @type = "text", @placeholder = "0123456789", @required = "required" })
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput4">ที่อยู่</label>
                        @Html.TextBoxFor(m => m.userinput.Contact, new { @class = "form-control my-text-input-custom", @type = "text", @placeholder = "ที่อยู่", @required = "required" })
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput5">หน้าที่</label>
                        <select asp-for="@Model.roleid" asp-items="Model.roledb" class="form-control my-select-box-custom" required>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                </div>
                <div class="col-6 text-right">
                    <button class="btn btn-primary" asp-page-handler="ToCreate"><i class="fas fa-check mr-2"></i>เพิ่ม</button>
                </div>
            </div>
        </div>
    </div>
</form>

StockVinul/stockproject/Pages/Stock/Admin/confirmstatus.cshtml
@page
@model stockproject.confirmstatusModel
@{
    ViewData["Title"] = "confirmstatus";
    Layout = "~/Pages/Shared/_Layoutadmin.cshtml";
}

@*<h1>confirmstatus</h1>*@
@*<div class="d-flex flex-row-reverse mb-2">
        <div class="">
            <form method="post">
                <button asp-page-handler="GoToCreateForm" class="btn btn-primary"><i class="fas fa-file-medical mr-2"></i>Create Form</button>
            </form>
        </div>
    </div>*@
<div class="row mt-5 mb-3">
    <div class="col-12 text-center">
        <h3>รายการเคลื่อนย้าย</h3>
    </div>
</div>
<div class="container-detail-form">
    <div class="wrap-detail-form">
        <form method="post">

            <div class="text-center">
                <h5 class="card-title">@ViewData["type"] </h5>
            </div>

            <div class="row justify-content-between">
                <div class="col-12 text-center mb-3">
                    สถานะรายการ:
                    @{
                        if (Model.formHeader.Status == "wait")
                        {
                            <span class="badge badge-secondary">กำลังรอยืนยัน</span>
                        }
                        else if (Model.formHeader.Status == "confirm")
                        {
                            <span class="badge badge-success">ยืนยันแล้ว</span>
                        }
                        else
                        {
                            <span class="badge badge-danger">ยกเลิกแล้ว</span>
                        }
                    }
                </div>
                <div class="col-6">
                    <p>สร้างโดย: @ViewData["name"]</p>
                </div>
                <div class="col-6">
                    <p>วันที่ทำรายการ: @ViewData["date"]</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-12 text-right">
                    @if (ViewData["status"].ToString() == "False")
                    {
                        <button asp-page-handler="DeleteForm" asp-route-formId="@ViewData["id"]" asp-route-typeform="@ViewData["type"]" class="btn btn-link text-danger"><i class="fas fa-trash-alt mr-2"></i>ยกเลิกรายการนี้</button>
                        <button asp-page-handler="EditForm" asp-route-formId="@ViewData["id"]" asp-route-typeform="@ViewData["type"]" class="btn btn-outline-info"><i class="fas fa-edit mr-2"></i>ยืนยันแก้ไขรายการนี้</button>
                    }
                    else
                    {
                        <button class="btn btn-link text-danger" disabled><i class="fas fa-trash-alt mr-2"></i>ยกเลิกรายการนี้</button>
                        <button class="btn btn-info" disabled><i class="fas fa-edit mr-2"></i>ยืนยันแก้ไขรายการนี้</button>
                    }
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="table-wrapper">
                        <table class="table table-hover my-table-custom">
                            <thead>
                                <tr class="text-center">
                                    <th>#</th>
                                    <th></th>
                                    <th>สินค้า</th>
                                    <th>จำนวน <small>(หน่วย)</small></th>
                                    <th>ราคา/หน่วย <small>(บาท)</small></th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < Model.list.Count; i++)
                                {
                                    <tr class="text-center">
                                        <td>@(i + 1)</td>
                                        <td>
                                            <span>
                                                <img class="img-table-view" src="~/pic/@Model.list[i].Picpath" width="277" height="180">
                                            </span>
                                        </td>
                                        <td>@Model.list[i].product</td>
                                        @*<td class="text-right">@Model.list[i].qty</td>*@
                                        <td style="width: 200px;">
                                            @Html.HiddenFor(m => m.list[i].productid)
                                            @if (ViewData["status"].ToString() == "False")
                                            {
                                                @Html.TextBoxFor(m => m.list[i].qty, new { @type = "number", @placeholder = "0", @class = "form-control my-text-input-custom", @required = true, @min = "1" })
                                            }
                                            else
                                            {
                                                @Html.TextBoxFor(m => m.list[i].qty, new { @type = "number", @placeholder = "0", @class = "form-control my-text-input-custom", @disabled = true })
                                            }
                                        </td>
                                        <td class="text-right pr-4">@Model.list[i].price</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </form>
        <div class="row mt-3">
            <div class="col-12">
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row text-right">
            <div class="col">
                @if (ViewData["status"].ToString() == "False")
                {
                    @if (ViewData["confirm"].ToString() == "Yes")
                    {
                        <form asp-page-handler="CONFIRM" method="post" class="d-inline">
                            <button class="btn btn-success"><i class="fas fa-check mr-2"></i>ยืนยัน</button>
                            <input type="hidden" name="id" value="@ViewData["id"]" />
                            <input type="hidden" name="type" value="@ViewData["type"]" />
                        </form>
                    }
                    else
                    {
                        <button class="btn btn-success" disabled><i class="fas fa-check mr-2"></i>ยืนยัน</button>
                    }

                    <form asp-page-handler="REJECT" method="post" class="d-inline">
                        <button class="btn btn-danger ml-2"><i class="fas fa-times mr-2"></i>ยกเลิก</button>
                        <input type="hidden" name="id" value="@ViewData["id"]" />
                        <input type="hidden" name="type" value="@ViewData["type"]" />
                    </form>
                }
                else
                {
                    <button class="btn btn-success" disabled><i class="fas fa-check mr-2"></i>ยืนยัน </button>
                    <button class="btn btn-danger ml-2" disabled><i class="fas fa-times mr-2"></i>ยกเลิก</button>
                }
            </div>
        </div>
    </div>
</div>