Pizza/Pizza/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Pizza.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pizza/Pizza/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Pizza.Enititys;

namespace Pizza.Pages
{
    public class IndexModel : PageModel
    {
        private readonly PizzaprojectContext db = new PizzaprojectContext();
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            try
            {
                // Verification.  
                if (this.User.Identity.IsAuthenticated)
                {
                    if (User.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).SingleOrDefault() == "True")
                    {
                        return RedirectToPage("Admin/summaryReport");
                    }
                    else
                    {
                    return RedirectToPage("User/Menu");

                    }
                    // Go to Home Page.  
                }
            }
            catch (Exception ex)
            {
                Console.Write(ex);
            }
            return Page();
        }
        public IActionResult OnPostGoToRegister()
        {
            return RedirectToPage("/Register");
        }
        public ActionResult OnPostLogIn()
        {
            if (username == null || password == null)
            {
                return Page();
            }
            Enititys.User user = new Enititys.User();
            user = (from t1 in db.User
                    where t1.Username == username && t1.Password == password
                    select t1).SingleOrDefault();

            if (user != null)
            {
                var claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.Name, user.Username));
                claims.Add(new Claim(ClaimTypes.NameIdentifier, user.Userid.ToString()));
                claims.Add(new Claim(ClaimTypes.Role, user.Isadmin.ToString()));
                
                //claims.Add(new Claim(ClaimTypes.Role, user.RoleId.ToString()));

                var claimIdenties = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimPrincipal = new ClaimsPrincipal(claimIdenties);
                var authenticationManager = Request.HttpContext;

                authenticationManager.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal, new AuthenticationProperties() { IsPersistent = false });

                //return RedirectToPage("/Stock/User/FormList");

                // return RedirectToPage("/Stock/Admin/Admin");
                //if (true) //user.RoleId == 1
               
                //{
                if (user.Isadmin)
                {
                    return RedirectToPage("Admin/summaryReport");

                }
                else
                {
                    return RedirectToPage("User/Menu");

                }

                //}
                //else
                //{
                //    return RedirectToPage("/Privacy");
                //}
                //return Page();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Invalid username or password.");
                return Page();
            }
        }
        public ActionResult OnPostLogOff()
        {
            try
            {
                // Setting.  
                var authenticationManager = Request.HttpContext;
                HttpContext.Session.Remove("menu");
                // Sign Out.  
                authenticationManager.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return this.RedirectToPage("/Index");
        }
        #region variable
        [BindProperty]
        [Required(ErrorMessage = "Please enter your username.")]
        public string username { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Please enter your password.")]
        public string password { get; set; }
        #endregion
    }
}

Pizza/Pizza/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Pizza.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pizza/Pizza/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Pizza.Enititys;

namespace Pizza.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly PizzaprojectContext db = new PizzaprojectContext();

        public void OnGet()
        {

        }
        public IActionResult OnPostGoToLogin()
        {
            return RedirectToPage("/Index");
        }
        public ActionResult OnPostRegister()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (username == null || password == null)
            {
                return Page();
            }
            Enititys.User user = new Enititys.User();
            user = (from t1 in db.User
                    where t1.Username == username
                    select t1).SingleOrDefault();

            if (user != null)
            {
                ModelState.AddModelError(string.Empty, "Username is already existed.");
                return Page();
            }
            else
            {
                Enititys.User newUser = new Enititys.User();
                newUser.Username = username;
                newUser.Password = password;
                newUser.Phone = phone;
                newUser.Email = email;
                newUser.Address = address;
                db.User.Add(newUser);
                db.SaveChanges();
                //ModelState.AddModelError(string.Empty, "This user has been created.");
                return RedirectToPage("/Index");
            }
        }
        #region variable
        [BindProperty]
        [Required(ErrorMessage = "Please enter your username.")]
        public string username { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Please enter your password.")]
        public string password { get; set; }
        [BindProperty]
        //[Required(ErrorMessage = "Please enter your password.")]
        public string phone { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Please enter your email.")]
        public string email { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Please enter your address.")]
        public string address { get; set; }
        #endregion
    }
}

Pizza/Pizza/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Login";
    Layout = "~/Pages/Shared/_LoginLayout.cshtml";
}

@*<div class="container h-100 w-100 d-flex">
        <div class="card m-auto login-block">
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div style="width: 300px; height: 300px;">

                        </div>

                    </div>
                    <div class="col">
                        <div class="text-center mt-3 mb-3">
                            <h2 class="text-white">
                                Login
                            </h2>
                        </div>
                        <div class="">
                            <form method="post" style="padding-top:5px">
                                <div class="form-group">
                                    <div class="input-group shadow-sm">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"> <i class="fas fa-user"></i></span>
                                        </div>
                                        @Html.TextBoxFor(m => m.username, new { @class = "form-control", @placeholder = "Username", required = "required" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group shadow-sm">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                                        </div>
                                        @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password", required = "required" })
                                    </div>
                                </div>
                                <div class="form-group float-right">
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <a class="nav-link text-white btn-link" asp-page="Register">Register</a>
                                    </div>
                                    <div class="col text-right">
                                        <button asp-page-handler="LogIn" class="btn btn-success"><i class="fas fa-sign-in-alt"></i> Login</button>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@

<style>
    .main {
        width: 85%;
        margin: 20px auto;
        position: relative;
        border-bottom: 1px solid #e6e6e6;
        padding: 20px 0;
    }

    .form-group .form-control {
        padding-left: 3.375rem;
        border: none;
        background-color: transparent;
        font-size: 1.4rem;
        color: #555555;
    }

    form .form-control:focus {
        border-color: #ced4da;
        box-shadow: none;
    }

    .form-group .form-control-icon {
        position: absolute;
        z-index: 2;
        display: block;
        width: 2.375rem;
        height: 2.375rem;
        line-height: 2.375rem;
        text-align: center;
        pointer-events: none;
    }

    .edit {
        height: calc(1.5em + .30rem + 1px);
        color: #555555;
        text-align: left;
        padding: 0 20px 0 80px;
        border-bottom: 1px solid #e6e6e6;
    }

    input {
        border: none;
        background-color: transparent;
    }

        input:focus,
        select:focus,
        textarea:focus,
        button:focus {
            outline: none;
        }

    .fa-user-circle-o {
        color: gray;
    }
</style>


@*<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@

<span class="login100-form-title p-b-41">
    Account Login
</span>
<form method="post" class="login100-form validate-form p-b-33 p-t-5">

    <div class="main">
        <div class="form-group">
            <span class="fa fa-user form-control-icon"></span>
            @Html.TextBoxFor(m => m.username, new { @type = "text", @class = "form-control input100 edit", @placeholder = "Username", required = "required" })

        </div>
    </div>

    @*<div class="wrap-input100 validate-input" data-validate="Enter username">

            @Html.TextBoxFor(m => m.username, new { @type = "text", @class = "input100", @placeholder = "Username", required = "required" })
            <span class="focus-input100" data-placeholder="&#xe82a;"></span>

        </div>*@

    @*<div class="wrap-input100 validate-input" data-validate="Enter password">

            @Html.PasswordFor(m => m.password, new { @type = "password", @class = "input100", @placeholder = "Password", required = "required" })
            <span class="focus-input100" data-placeholder="&#xe80f;"></span>
        </div>*@

    <div class="main">
        <div class="form-group">
            <span class="fa fa-lock form-control-icon"></span>
            @Html.TextBoxFor(m => m.password, new { @type = "password", @class = "form-control input100 edit", @placeholder = "Password", required = "required" })

        </div>
    </div>


    <div class="container-login100-form-btn m-t-32 m-b-10">
        <button asp-page-handler="LogIn" class="login100-form-btn">
            Login
        </button>


    </div>
    <p style="text-align: center;">Not Registered ? <a style="color:tomato" asp-page="Register">Create an account</a></p>

</form>

<div>
    @Html.ValidationSummary(false, "", new { @class = "text-danger", @style = "left: 50px" })
</div>

Pizza/Pizza/Pages/Register.cshtml
@page
@model Pizza.Pages.RegisterModel
@{
    ViewData["Title"] = "Register";
    Layout = "~/Pages/Shared/_LoginLayout.cshtml";
}
    <style>
        .main {
            width: 85%;
            margin: 3px auto;
            position: relative;
            border-bottom: 1px solid #e6e6e6;
            padding: 15px 0;
        }

        .form-group .form-control {
            padding-left: 3.375rem;
            border: none;
            background-color: transparent;
            font-size: 1.4rem;
            color: #555555;
        }

        form .form-control:focus {
            border-color: #ced4da;
            box-shadow: none;
        }

        .form-group .form-control-icon {
            position: absolute;
            z-index: 2;
            display: block;
            width: 2.375rem;
            height: 2.375rem;
            line-height: 2.375rem;
            text-align: center;
            pointer-events: none;
        }

        .edit {
            height: calc(1.5em + .30rem + 1px);
            color: #555555;
            text-align: left;
            padding: 0 20px 0 80px;
            border-bottom: 1px solid #e6e6e6;
        }

        input {
            border: none;
            background-color: transparent;
        }

            input:focus,
            select:focus,
            textarea:focus,
            button:focus {
              outline: none;
            }

        .fa-user-circle-o {
            color: gray;
        }
        .color{
        background: #d4d318;
        background: -webkit-linear-gradient(left, #249bd5, #18d4c4, #b2e21a);
        }
    </style>

@*<div class="container h-100 w-100 d-flex">
    <div class="card m-auto registor-block">
        <div class="card-body">
            <div class="row">
                <div class="col" style="width: 300px; height: 300px;">
                </div>
                <div class="col">
                    <div class="text-center mt-3 mb-3">
                        <h2 class="text-white">
                            Register
                        </h2>
                    </div>
                    <div class="">
                        <form method="post" style="padding-top:5px">
                            <div class="form-group">
                                <div class="input-group shadow-sm">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"> <i class="fas fa-user"></i></span>
                                    </div>
                                    @Html.TextBoxFor(m => m.username, new { @class = "form-control", @placeholder = "Username", required = "required" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group shadow-sm">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                                    </div>
                                    @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password", required = "required" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group shadow-sm">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-map-marked"></i></span>
                                    </div>
                                    @Html.TextAreaFor(m => m.address, new { @class = "form-control", @placeholder = "Address", required = "required" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group shadow-sm">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-mobile"></i></span>
                                    </div>
                                    @Html.TextBoxFor(m => m.phone, new { @class = "form-control", @placeholder = "Phone" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group shadow-sm">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                    </div>
                                    @Html.TextBoxFor(m => m.email, new { @class = "form-control", @placeholder = "Email", required = "required" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-8">
                                    <a class="nav-link text-white" asp-page="Index">Already registed</a>
                                </div>
                                <div class="col-4 text-right">
                                    <button asp-page-handler="Register" class="btn btn-success"><i class="fas fa-angle-right"></i> Submit</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>*@

<span class="login100-form-title p-b-41">
    Register
</span>
<form method="post" class="login100-form validate-form">

    <div class="main">
        <div class="form-group">
            <span class="fa fa-user form-control-icon"></span>
            @Html.TextBoxFor(m => m.username, new { @class = "form-control input100 edit", @placeholder = "Username", required = "required" })
        </div>
    </div>
    <div class="main">
        <div class="form-group">
            <span class="fa fa-key form-control-icon"></span>
            @Html.PasswordFor(m => m.password, new { @class = "form-control input100 edit", @placeholder = "Password", required = "required" })
        </div>
    </div>
    <div class="main">
        <div class="form-group">
            <span class="fa fa-map-marked form-control-icon"></span>
            @Html.TextAreaFor(m => m.address, new { @class = "form-control input100 edit", @placeholder = "Address", required = "required" })
        </div>
    </div>

    <div class="main">
        <div class="form-group">
            <span class="fa fa-mobile form-control-icon"></span>
            @Html.TextBoxFor(m => m.phone, new { @class = "form-control input100 edit", @placeholder = "Phone" })
        </div>
    </div>
    <div class="main">
        <div class="form-group">
            <span class="fa fa-envelope form-control-icon"></span>
            @Html.TextBoxFor(m => m.email, new { @class = "form-control input100 edit", @placeholder = "Email", required = "required" })
        </div>
    </div>

    <div class="container-login100-form-btn m-t-20 m-b-10">
        <button asp-page-handler="Register" class="login100-form-btn color">
            Submit
        </button>

    </div>
    <p style="text-align: center;"><a style="color:tomato" asp-page="Index">Already registed</a></p>
    <div class="row">
        <div class="col">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        </div>
    </div>

</form>