StockVinul/stockproject/Pages/Stock/Admin/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.ExternalModels;

namespace stockproject.Pages.Admin
{
    public class AdminModel : PageModel
    {
        /*
         * หน้า admin หน้านี้มีไว้ดูสรุปว่ามีบิลกี่บิลในระบบ ณ ปัจจุบัน
         * คำสั่งนี้มีไว้ขอใช้ Database โดยจะใช้ผ่านตัวแปรที่ชื่อว่า db
         */

        private readonly StockprojectContext db = new StockprojectContext();

        //คุณสมบัติ BindProperty ทำให้ตัวแปรที่อยู่ภายใต้อันนี้ (แค่1ตัว) สามารถรับค่าผ่านไปมาระหว่างหน้าเว็ปและหน้าที่เขียนโค้ดได้
        [BindProperty]
        public List<QueryAdmin_FormIn> listFromIn { get; set; } = new List<QueryAdmin_FormIn>();

        [BindProperty]
        public List<QueryAdmin_FormOut> listFormOut { get; set; } = new List<QueryAdmin_FormOut>();
        public List<string> id { get; set; }

        [BindProperty]
        public int totalIn { get; set; }
        [BindProperty]
        public int confirmedIn { get; set; }
        [BindProperty]
        public int rejectedIn { get; set; }
        [BindProperty]
        public int waittingIn { get; set; }

        [BindProperty]
        public int totalOut { get; set; }
        [BindProperty]
        public int confirmedOut { get; set; }
        [BindProperty]
        public int rejectedOut { get; set; }
        [BindProperty]
        public int waittingOut { get; set; }

        //ฟังชั่น onget จะเรียกทุกครั้งที่มีการเข้าถึงหน้านี้ เช่น การโหลดหน้าเว็ปหน้านี้ หรือเข้า Url นี้โดย OnGet ต้องเขียนแบบนี้เท่านั้น และตามด้วยชื่อฟังชั่น แต่ถ้าไม่มีมันจะคือ Default
        public void OnGet()
        {

            /*
             * ประกาศตัวแปร q2ให้มารับค่าจากดาต้าเบสในตาราง formin
             * var คือการไม่กำหนด Type คอมไพล์เลอร์จะหา Type ที่เหมาะสมให้ตัวแปรนั้นเอง
             * from t1 in db.FormIn คือ ตั้งตัวแปรชื่อว่า t1 เอาค่าในดาต้าเบส -> ตาราง FormIn
             * select new  เลือกใหม่ เลือกคอลัม FormInid,Status,Createdate
             * { t1.FormInid, t1.Status, t1.Createdate })*/

            var q2 = (from t1 in db.FormIn
                      select new { t1.FormInid, t1.Status, t1.Createdate });

            //วนลูป q2 โดย foreach จะวนลูปถึงตัวสุดท้ายโดนอัตโนมัติ
            foreach (var item in q2)
            {
                //สร้างตัวแปร QueryFormIn มี Type เป็นQueryAdmin_FormIn มาเพื่อกำหนดค่าลงในตัวแปรเพื่อนำไปใช้ต่อ

                QueryAdmin_FormIn QueryFormIn = new QueryAdmin_FormIn();

                QueryFormIn.id = item.FormInid; /*กำหนดค่า QueryFormIn.id = ค่าทางด้านขวาที่เอามาจากดาต้าเบส*/
                QueryFormIn.Subject = "FormIn";
                QueryFormIn.Createdate = item.Createdate;
                QueryFormIn.Status = item.Status;
                listFromIn.Add(QueryFormIn); /*เพิ่มค่าลงตัวแปร listFromIn โดยใช้คำสั่ง Add(ค่าที่ต้องการจะใส่เข้าไป)*/

                //เมื่อทำแบบนี้จนหมดตัวแปร listFromIn จะมีขนาดเท่ากับ q2 หรือคือค่าที่นำมาจากดาต้าเบส แต่ค่าใน listFromInจะเพิ่มเติมคำว่า FormIn เพื่อแยกว่านี่คือการนำเข้าหรือออก
            }

            //q3 ทำเหมือน q2 แตกต่างที่นี่คือ FormOut
            var q3 = (from t1 in db.FormOut
                      select new { t1.FormOutid, t1.Status, t1.Createdate });


            foreach (var item in q3)
            {
                QueryAdmin_FormOut QueryFormOut = new QueryAdmin_FormOut();
                QueryFormOut.id = item.FormOutid;
                QueryFormOut.Subject = "FormOut";
                QueryFormOut.Createdate = item.Createdate;
                QueryFormOut.Status = item.Status;
                listFormOut.Add(QueryFormOut);
            }
            summayReport();
        }

        /*
         * OnPost คือคำสั่งการกำหนด methord ให้ทำงานแบบ post หรือคือการส่งค่าผ่าน <from></from>
         * โดย OnPost ต้องเขียนแบบนี้เท่านั้นและตามด้วยชื่อฟังชั่น โดยทำผ่าน action ที่เรียกว่า ActionResult เท่านั้น
         */

        //ฟังชั่นนี้ไว้สำหรับการรับค่าและส่งไปให้หน้า confirmstatus โดยมี Parmmeter 2 ตัวคือ id ของ form และชนิดของ formt หรือtype
        public ActionResult OnPostVALUE(int id, string type)
        {
            /*คำสั่งส่งค่าข้ามหน้า ต้องทำผ่าน action ActionResult เท่านั้น  
             * โดย "./confirmstatus" คือการสั่งให้ไปที่หน้านี้ . (จุด) คือหมายถึงลำดับชั้นไฟล์เดียวกัน หรือคือให้ออกจากหน้านี้ไปต้องออกจากโฟล์เดอร์นี้
             * .. (จุดจุด) หมายถึงให้ออกจากโฟล์เดอรืนี้ 
             * "OnGet" คือการสั่งให้ไปที่ฟังชั่นนี้ 
             * new { formid = id, formtype = type } สั่งให้ส่ง Parmeter 2ตัวคือ id,type
             
             */
            return RedirectToPage("./confirmstatus", "OnGet", new { formid = id, formtype = type });
        }

        //ฟังชีั่น GoToCreateForm หน้าที่คือถ้ากดปุ่มนี้จะเปี่ลยหน้าไปที่ Product
        public ActionResult OnPostGoToCreateForm()
        {
            return RedirectToPage("/Stock/Product");
        }

       public void summayReport()
        {
            var inList = (from t1 in db.FormIn select t1);
            totalIn = inList.Count();
            confirmedIn = inList.Where(c => c.Status == "confirm" && c.Isstatus == true).Count();
            rejectedIn = inList.Where(c => c.Status == "reject" && c.Isstatus == true).Count();
            waittingIn = inList.Where(c => c.Status == "wait" && c.Isstatus == false).Count();
            var outList = (from t1 in db.FormOut select t1);
            totalOut = outList.Count();
            confirmedOut = outList.Where(c => c.Status == "confirm" && c.Isstatus == true).Count();
            rejectedOut = outList.Where(c => c.Status == "reject" && c.Isstatus == true).Count();
            waittingOut = outList.Where(c => c.Status == "wait" && c.Isstatus == false).Count();
        }

    }
}

StockVinul/stockproject/Pages/Stock/Admin/CreateUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using stockproject.Enititys;

namespace stockproject
{
    public class CreateUserModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();

        public void OnGet()
        {
            roledb = (from t1 in db.Role
                      select new SelectListItem
                      {
                          Value = t1.Roleid.ToString(),
                          Text = t1.Rolename
                      }).ToList();
        }
        public ActionResult OnPostToCreate()
        {
           
            User user = new User();
            user.Username = userinput.Username;
            user.Password = userinput.Password;
            user.FullName = userinput.FullName;
            user.Phone = userinput.Phone;
            user.Contact = userinput.Contact;
            user.Roleid = Convert.ToInt32(roleid);

            db.User.Add(user);
            db.SaveChanges();

            return RedirectToPage("./Admin", "OnGet");
        }



        [BindProperty]
        public string roleid { get; set; }
        [BindProperty]
        public User userinput { get; set; } = new User();
        public List<SelectListItem> roledb { get; set; } = new List<SelectListItem>();

    }
}

StockVinul/stockproject/Pages/Stock/User/FormDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.ExternalModels;

namespace stockproject
{
    public class FormDetailModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();
        public ActionResult OnGet(int formId, string formtype)
        {
            var userid = Convert.ToInt32(User.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault());
            var Username = User.Claims.Where(c => c.Type == ClaimTypes.Name).Select(c => c.Value).SingleOrDefault();
            ViewData["name"] = Username;
            if (formtype == "in")
            {
                ViewData["id"] = formId;
                ViewData["type"] = "รายการนำสินค้าเข้า";
                formHeader = db.FormIn.Select(a => new ResultForm()
                {
                    Formid = a.FormInid,
                    IsIn = true,
                    IsStatus = a.Isstatus,
                    Status = a.Status,
                    Createdate = a.Createdate,
                    Statusdate = a.Statusdate,
                    Userid = a.Userid

                }).Single(a => a.Formid == formId && a.Userid == userid);
                if (formHeader.Userid == userid)
                {
                    ViewData["Ckuser"] = "Yes";
                    ViewData["typeForm"] = "Formin";
                    ViewData["IDForm"] = formId;
                }
                else
                {
                    ViewData["Ckuser"] = "No";
                }
                formDetail = db.ProductFormIn.Where(c => c.FormInid == formId).Select(a => new DetailForm()
                {
                    ProductformId = a.ProductformInid,
                    ProductName = db.Product.Where(pro => pro.Productid == a.ProductId).Single().Productname,
                    FormId = a.FormInid,
                    Price = a.Price,
                    ProductId = a.ProductId,
                    Qty = a.Qty,
                    Status = a.Status,
                    Picpath = db.Product.Where(pro => pro.Productid == a.ProductId).Single().Picpath
                }
                ).ToList();
            }
            else
            {
                ViewData["id"] = formId;
                ViewData["type"] = "รายการจ่ายสินค้าออก";
                formHeader = db.FormOut.Select(a => new ResultForm()
                {
                    Formid = a.FormOutid,
                    IsIn = false,
                    IsStatus = a.Isstatus,
                    Status = a.Status,
                    Createdate = a.Createdate,
                    Statusdate = a.Statusdate,
                    Userid = a.Userid
                }).Single(a => a.Formid == formId && a.Userid == userid);
                if (formHeader.Userid == userid)
                {
                    ViewData["Ckuser"] = "Yes";
                    ViewData["typeForm"] = "Formout";
                    ViewData["IDForm"] = formId;
                }
                else
                {
                    ViewData["Ckuser"] = "No";
                }
                formDetail = db.ProductFormOut.Where(c => c.FormOutid == formId).Select(a => new DetailForm()
                {
                    ProductformId = a.ProductformOutid,
                    ProductName = db.Product.Where(pro => pro.Productid == a.ProductId).Single().Productname,
                    FormId = a.FormOutid,
                    Price = a.Price,
                    ProductId = a.ProductId,
                    Qty = a.Qty,
                    Status = a.Status,
                    Picpath = db.Product.Where(pro => pro.Productid == a.ProductId).Single().Picpath
                }
                ).ToList();
            }
            ViewData["date"] = formHeader.Createdate;
            if (formHeader.IsStatus == true)
            {
                ViewData["status"] = "True";
            }
            else
            {
                ViewData["status"] = "False";
            }
            return Page();
        }
        public ActionResult OnPostEditForm(string typeform)
        {
            //วนทุกสินค้าที่เลือกมา
            foreach (var item in formDetail)
            {
                // ถ้ามีรายการสินค้าใด ที่มีจำนวนเป็น 0 จะให้แสดงข้อความแจ้งเตือนที่หน้าจอ และให้กรอกใหม่
                if (item.Qty <= 0)
                {
                    ModelState.AddModelError(string.Empty, "กรุณากรอกจำนวนสินค้าให้ครบถ้วน (มีสินค้าบางรายการที่จำนวนไม่ถูกต้อง)");
                    return OnGet(formHeader.Formid, (typeform == "Formin") ? "in" : "out");
                }
            }
            string formType;

            if (typeform == "Formin")
            {
                formType = "in";
                FormIn formIn = new FormIn();

                formIn = (from t1 in db.FormIn
                          where t1.FormInid == formHeader.Formid
                          select t1).SingleOrDefault();

                if (formIn.Isstatus == false)
                {
                    foreach (var item in formDetail)
                    {

                        var profornin = (from t1 in db.ProductFormIn
                                         where t1.ProductId == item.ProductId && t1.FormInid == item.FormId
                                         select t1).SingleOrDefault();

                        if (item.Qty != null)
                        {
                            profornin.Qty = item.Qty.Value;

                            db.SaveChanges();
                        }
                    }
                }
            }
            else
            {
                formType = "out";
                FormOut formOut = new FormOut();

                formOut = (from t1 in db.FormOut
                           where t1.FormOutid == formHeader.Formid
                           select t1).SingleOrDefault();

                if (formOut.Isstatus == false)
                {
                    foreach (var item in formDetail)
                    {
                        var profornin = (from t1 in db.Product
                                         where t1.Productid == item.ProductId
                                         select t1).SingleOrDefault();

                        if (item.Qty > profornin.Qty)
                        {
                            ModelState.AddModelError(string.Empty, "'" + item.ProductName + "' ของใน Stock มีไม่พอ");
                            return OnGet(formHeader.Formid, formType);
                        }
                    }

                    foreach (var item in formDetail)
                    {
                        var profornin = (from t1 in db.ProductFormOut
                                         where t1.ProductId == item.ProductId && t1.FormOutid == item.FormId
                                         select t1).SingleOrDefault();

                        if (item.Qty != null)
                        {
                            profornin.Qty = item.Qty.Value;

                            db.SaveChanges();
                        }
                    }
                }
            }
            //foreach (var item in collection)
            //{

            //}
            //var a = formDetail;
            //var b = formHeader;
            //ModelState.Clear();
            return OnGet(formHeader.Formid, formType);
        }

        public ActionResult OnPostGoToCreateForm()
        {
            return RedirectToPage("/Stock/Product");
        }
        public ActionResult OnPostDeleteForm(int formId, string typeform)
        {
            if (typeform == "Formin")
            {

                var query = from c in db.FormIn where (c.FormInid == formId) select c;
                foreach (FormIn c in query)
                {
                    db.FormIn.Remove(c);

                }

                var query2 = from c2 in db.ProductFormIn where (c2.FormInid == formId) select c2;
                foreach (ProductFormIn c2 in query2)
                {
                    db.ProductFormIn.Remove(c2);

                }
                db.SaveChanges();

            }
            else
            {
                var query = from c in db.FormOut where (c.FormOutid == formId) select c;
                foreach (FormOut c in query)
                {
                    db.FormOut.Remove(c);

                }

                var query2 = from c2 in db.ProductFormOut where (c2.FormOutid == formId) select c2;
                foreach (ProductFormOut c2 in query2)
                {
                    db.ProductFormOut.Remove(c2);

                }
                db.SaveChanges();
            }
            return RedirectToPage("/Stock/User/User");
        }

        [BindProperty]
        public ResultForm formHeader { get; set; }
        [BindProperty]
        public List<DetailForm> formDetail { get; set; } = new List<DetailForm>();
    }
}

StockVinul/stockproject/Pages/Stock/User/FormDetail.cshtml
@page
@model stockproject.FormDetailModel
@{
    ViewData["Title"] = "FormDetail";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<div class="row mt-5 mb-3">
    <div class="col-12 text-center">
        <h3>รายการเคลื่อนย้าย</h3>
    </div>
</div>
<div class="container-detail-form">
    <div class="wrap-detail-form">
        <form method="post">

            <div class="text-center">
                <h5 class="card-title">@ViewData["type"] </h5>
            </div>

            <div class="row justify-content-between">
                <div class="col-12 text-center mb-3">
                    สถานะรายการ:
                    @{
                        if (Model.formHeader.Status == "wait")
                        {
                            <span class="badge badge-secondary">กำลังรอยืนยัน</span>
                        }
                        else if (Model.formHeader.Status == "confirm")
                        {
                            <span class="badge badge-success">ยืนยันแล้ว</span>
                        }
                        else
                        {
                            <span class="badge badge-danger">ยกเลิกแล้ว</span>
                        }
                    }
                </div>
                <div class="col-6">
                    <p>สร้างโดย: @ViewData["name"]</p>
                </div>
                <div class="col-6">
                    <p>วันที่ทำรายการ: @ViewData["date"]</p>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-12 text-right">
                    @if (ViewData["Ckuser"] == "Yes")
                    {
                        @if (ViewData["status"] == "False")
                        {
                            <button asp-page-handler="DeleteForm" asp-route-formId="@ViewData["IDForm"]" asp-route-typeform="@ViewData["typeForm"]" class="btn btn-link text-danger"><i class="fas fa-trash-alt mr-2"></i>ยกเลิกรายการนี้</button>

                            <button asp-page-handler="EditForm" asp-route-formId="@ViewData["IDForm"]" asp-route-typeform="@ViewData["typeForm"]" class="btn btn-outline-info"><i class="fas fa-edit mr-2"></i>ยืนยันแก้ไขรายการนี้</button>
                        }
                        else
                        {
                            <button class="btn btn-link text-danger" disabled><i class="fas fa-trash-alt mr-2"></i>ยกเลิกรายการนี้</button>
                            <button class="btn btn-info" disabled><i class="fas fa-edit mr-2"></i>ยืนยันแก้ไขรายการนี้</button>
                        }
                    }
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="table-wrapper">
                        <table class="table table-hover my-table-custom">
                            <thead>
                                <tr class="text-center">
                                    <th>#</th>
                                    <th></th>
                                    <th>สินค้า</th>
                                    <th>จำนวน <small>(หน่วย)</small></th>
                                    <th>ราคา/หน่วย <small>(บาท)</small></th>
                                </tr>
                            </thead>

                            <tbody>
                                @for (var i = 0; i < Model.formDetail.Count; i++)
                                {
                                    <tr class="text-center">
                                        <td>
                                            <label name="[@i].No">@(i + 1)</label>
                                        </td>
                                        <td>
                                            <span>
                                                <img class="img-table-view" src="~/pic/@Model.formDetail[i].Picpath" width="277" height="180">
                                            </span>
                                        </td>
                                        <td>
                                            <label name="[@i].ProductName">@Model.formDetail[i].ProductName</label>
                                        </td>
                                        <td style="width: 200px;">
                                            @Html.HiddenFor(m => m.formDetail[i].ProductformId)
                                            @Html.HiddenFor(m => m.formDetail[i].FormId)
                                            @Html.HiddenFor(m => m.formDetail[i].ProductName)
                                            @Html.HiddenFor(m => m.formDetail[i].ProductId)
                                            @Html.HiddenFor(m => m.formDetail[i].Price)
                                            @Html.HiddenFor(m => m.formDetail[i].Status)
                                            @if (ViewData["status"].ToString() == "False")
                                            {
                                                @Html.TextBoxFor(m => m.formDetail[i].Qty, new { @type = "number", @placeholder = "0", @class = "form-control my-text-input-custom", @required = true, @min = "1" })

                                            }
                                            else
                                            {
                                                @Html.TextBoxFor(m => m.formDetail[i].Qty, new { @type = "number", @placeholder = "0", @class = "form-control my-text-input-custom", @required = true, @min = "1", @disabled = true })
                                            }
                                        </td>
                                        <td class="text-right pr-4">@Model.formDetail[i].Price</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-12">
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                </div>
            </div>
        </form>
    </div>
</div>




@*<div class="d-flex justify-content-between mb-3">
        <div>
            <h2>
                Form-in details
            </h2>
        </div>
        <div>
            <form method="post">
                <button asp-page-handler="GoToCreateForm" class="btn btn-primary">Create Form</button>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <div class="row">

                <div class="col-auto mr-auto">  Form Detail</div>
                <div class="col-auto">
                    @if (ViewData["Ckuser"] == "Yes")
                    {

                        <form method="post">
                            <button asp-page-handler="DeleteForm" asp-route-formId="@ViewData["IDForm"]" asp-route-typeform="@ViewData["typeForm"]" class="btn btn-danger">Delete Form</button>
                        </form>
                    }
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-around mb-3">
                <div>
                    Created By:@Model.formHeader.Userid
                </div>
                <div>
                    Created Date: @Model.formHeader.Createdate
                </div>
            </div>
            <table class="table table-striped border">
                <tr class="text-center">
                    <th>#</th>
                    <th>Product name</th>
                    <th>Qty</th>
                    <th>Price</th>
                </tr>
                @for (var i = 0; i < Model.formDetail.Count; i++)
                {
                    <tr class="text-center">
                        <td>
                            <label name="[@i].No">@(i + 1)</label>
                        </td>
                        <td class="text-left">
                            <label name="[@i].ProductName">@Model.formDetail[i].ProductName</label>
                        </td>
                        <td class="text-right">
                            <label name="[@i].Qty">@Model.formDetail[i].Qty</label>
                        </td>
                        <td class="text-right">
                            <label name="[@i].Price">@Model.formDetail[i].Price</label>
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="d-flex justify-content-around mb-3">
            <div>
                Status:
                @{
                    if (Model.formHeader.Status == "wait")
                    {
                        <span class="badge badge-secondary">Waiting</span>
                    }
                    else if (Model.formHeader.Status == "comfirm")
                    {
                        <span class="badge badge-success">Approved</span>
                    }
                    else
                    {
                        <span class="badge badge-danger">Rejected</span>
                    }
                }
            </div>
        </div>

    </div>*@