StockVinul/stockproject/Pages/Stock/Admin/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.ExternalModels;

namespace stockproject.Pages.Admin
{
    public class AdminModel : PageModel
    {
        /*
         * หน้า admin หน้านี้มีไว้ดูสรุปว่ามีบิลกี่บิลในระบบ ณ ปัจจุบัน
         * คำสั่งนี้มีไว้ขอใช้ Database โดยจะใช้ผ่านตัวแปรที่ชื่อว่า db
         */

        private readonly StockprojectContext db = new StockprojectContext();

        //คุณสมบัติ BindProperty ทำให้ตัวแปรที่อยู่ภายใต้อันนี้ (แค่1ตัว) สามารถรับค่าผ่านไปมาระหว่างหน้าเว็ปและหน้าที่เขียนโค้ดได้
        [BindProperty]
        public List<QueryAdmin_FormIn> listFromIn { get; set; } = new List<QueryAdmin_FormIn>();

        [BindProperty]
        public List<QueryAdmin_FormOut> listFormOut { get; set; } = new List<QueryAdmin_FormOut>();
        public List<string> id { get; set; }

        [BindProperty]
        public int totalIn { get; set; }
        [BindProperty]
        public int confirmedIn { get; set; }
        [BindProperty]
        public int rejectedIn { get; set; }
        [BindProperty]
        public int waittingIn { get; set; }

        [BindProperty]
        public int totalOut { get; set; }
        [BindProperty]
        public int confirmedOut { get; set; }
        [BindProperty]
        public int rejectedOut { get; set; }
        [BindProperty]
        public int waittingOut { get; set; }

        //ฟังชั่น onget จะเรียกทุกครั้งที่มีการเข้าถึงหน้านี้ เช่น การโหลดหน้าเว็ปหน้านี้ หรือเข้า Url นี้โดย OnGet ต้องเขียนแบบนี้เท่านั้น และตามด้วยชื่อฟังชั่น แต่ถ้าไม่มีมันจะคือ Default
        public void OnGet()
        {

            /*
             * ประกาศตัวแปร q2ให้มารับค่าจากดาต้าเบสในตาราง formin
             * var คือการไม่กำหนด Type คอมไพล์เลอร์จะหา Type ที่เหมาะสมให้ตัวแปรนั้นเอง
             * from t1 in db.FormIn คือ ตั้งตัวแปรชื่อว่า t1 เอาค่าในดาต้าเบส -> ตาราง FormIn
             * select new  เลือกใหม่ เลือกคอลัม FormInid,Status,Createdate
             * { t1.FormInid, t1.Status, t1.Createdate })*/

            var q2 = (from t1 in db.FormIn
                      select new { t1.FormInid, t1.Status, t1.Createdate });

            //วนลูป q2 โดย foreach จะวนลูปถึงตัวสุดท้ายโดนอัตโนมัติ
            foreach (var item in q2)
            {
                //สร้างตัวแปร QueryFormIn มี Type เป็นQueryAdmin_FormIn มาเพื่อกำหนดค่าลงในตัวแปรเพื่อนำไปใช้ต่อ

                QueryAdmin_FormIn QueryFormIn = new QueryAdmin_FormIn();

                QueryFormIn.id = item.FormInid; /*กำหนดค่า QueryFormIn.id = ค่าทางด้านขวาที่เอามาจากดาต้าเบส*/
                QueryFormIn.Subject = "FormIn";
                QueryFormIn.Createdate = item.Createdate;
                QueryFormIn.Status = item.Status;
                listFromIn.Add(QueryFormIn); /*เพิ่มค่าลงตัวแปร listFromIn โดยใช้คำสั่ง Add(ค่าที่ต้องการจะใส่เข้าไป)*/

                //เมื่อทำแบบนี้จนหมดตัวแปร listFromIn จะมีขนาดเท่ากับ q2 หรือคือค่าที่นำมาจากดาต้าเบส แต่ค่าใน listFromInจะเพิ่มเติมคำว่า FormIn เพื่อแยกว่านี่คือการนำเข้าหรือออก
            }

            //q3 ทำเหมือน q2 แตกต่างที่นี่คือ FormOut
            var q3 = (from t1 in db.FormOut
                      select new { t1.FormOutid, t1.Status, t1.Createdate });


            foreach (var item in q3)
            {
                QueryAdmin_FormOut QueryFormOut = new QueryAdmin_FormOut();
                QueryFormOut.id = item.FormOutid;
                QueryFormOut.Subject = "FormOut";
                QueryFormOut.Createdate = item.Createdate;
                QueryFormOut.Status = item.Status;
                listFormOut.Add(QueryFormOut);
            }
            summayReport();
        }

        /*
         * OnPost คือคำสั่งการกำหนด methord ให้ทำงานแบบ post หรือคือการส่งค่าผ่าน <from></from>
         * โดย OnPost ต้องเขียนแบบนี้เท่านั้นและตามด้วยชื่อฟังชั่น โดยทำผ่าน action ที่เรียกว่า ActionResult เท่านั้น
         */

        //ฟังชั่นนี้ไว้สำหรับการรับค่าและส่งไปให้หน้า confirmstatus โดยมี Parmmeter 2 ตัวคือ id ของ form และชนิดของ formt หรือtype
        public ActionResult OnPostVALUE(int id, string type)
        {
            /*คำสั่งส่งค่าข้ามหน้า ต้องทำผ่าน action ActionResult เท่านั้น  
             * โดย "./confirmstatus" คือการสั่งให้ไปที่หน้านี้ . (จุด) คือหมายถึงลำดับชั้นไฟล์เดียวกัน หรือคือให้ออกจากหน้านี้ไปต้องออกจากโฟล์เดอร์นี้
             * .. (จุดจุด) หมายถึงให้ออกจากโฟล์เดอรืนี้ 
             * "OnGet" คือการสั่งให้ไปที่ฟังชั่นนี้ 
             * new { formid = id, formtype = type } สั่งให้ส่ง Parmeter 2ตัวคือ id,type
             
             */
            return RedirectToPage("./confirmstatus", "OnGet", new { formid = id, formtype = type });
        }

        //ฟังชีั่น GoToCreateForm หน้าที่คือถ้ากดปุ่มนี้จะเปี่ลยหน้าไปที่ Product
        public ActionResult OnPostGoToCreateForm()
        {
            return RedirectToPage("/Stock/Product");
        }

       public void summayReport()
        {
            var inList = (from t1 in db.FormIn select t1);
            totalIn = inList.Count();
            confirmedIn = inList.Where(c => c.Status == "confirm" && c.Isstatus == true).Count();
            rejectedIn = inList.Where(c => c.Status == "reject" && c.Isstatus == true).Count();
            waittingIn = inList.Where(c => c.Status == "wait" && c.Isstatus == false).Count();
            var outList = (from t1 in db.FormOut select t1);
            totalOut = outList.Count();
            confirmedOut = outList.Where(c => c.Status == "confirm" && c.Isstatus == true).Count();
            rejectedOut = outList.Where(c => c.Status == "reject" && c.Isstatus == true).Count();
            waittingOut = outList.Where(c => c.Status == "wait" && c.Isstatus == false).Count();
        }

    }
}

StockVinul/stockproject/Pages/Stock/Admin/CreateUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using stockproject.Enititys;

namespace stockproject
{
    public class CreateUserModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();

        public void OnGet()
        {
            roledb = (from t1 in db.Role
                      select new SelectListItem
                      {
                          Value = t1.Roleid.ToString(),
                          Text = t1.Rolename
                      }).ToList();
        }
        public ActionResult OnPostToCreate()
        {
           
            User user = new User();
            user.Username = userinput.Username;
            user.Password = userinput.Password;
            user.FullName = userinput.FullName;
            user.Phone = userinput.Phone;
            user.Contact = userinput.Contact;
            user.Roleid = Convert.ToInt32(roleid);

            db.User.Add(user);
            db.SaveChanges();

            return RedirectToPage("./Admin", "OnGet");
        }



        [BindProperty]
        public string roleid { get; set; }
        [BindProperty]
        public User userinput { get; set; } = new User();
        public List<SelectListItem> roledb { get; set; } = new List<SelectListItem>();

    }
}

StockVinul/stockproject/Pages/Stock/CreateForm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;

namespace stockproject.Pages.Stock
{
    public class CreateFormModel : PageModel
    {
        private readonly StockprojectContext db = new StockprojectContext();
        public ActionResult OnGet(List<int> proid = null)
        {
            products.Clear();
            foreach (var item in proid)
            {
                var aa = (from t1 in db.Product
                          where t1.Productid == item
                          select t1).SingleOrDefault();

                products.Add(aa);
            }

            return Page();
        }

        public ActionResult OnPostCreate()
        {
            //วนทุกสินค้าที่เลือกมา
            foreach (var item in products)
            {
                // ถ้ามีรายการสินค้าใด ที่มีจำนวนเป็น 0 จะให้แสดงข้อความแจ้งเตือนที่หน้าจอ และให้กรอกใหม่
                if (item.Qty <= 0)
                {
                    ModelState.AddModelError(string.Empty, "กรุณากรอกจำนวนสินค้าให้ครบถ้วน (มีสินค้าบางรายการที่จำนวนไม่ถูกต้อง)");
                    proid = products.Select(c => c.Productid).ToList();
                    OnGet(proid);
                    return Page();
                }
            }
            var userid = Convert.ToInt32(User.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault());

            var aa = products;
            var a = formId;

            if (a == "1") // in
            {
                int id = 0;
                FormIn formIn = new FormIn();
                //var a = User.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).SingleOrDefault())
                formIn.Userid = userid; //this.User.Identity.Name
                //formIn.Status = false;
                formIn.Createdate = DateTime.Now;

                db.FormIn.Add(formIn);

                db.SaveChanges();
                id = formIn.FormInid;

                foreach (var item in products)
                {
                    ProductFormIn productFormIns = new ProductFormIn();

                    productFormIns.FormInid = id;
                    productFormIns.ProductId = item.Productid;
                    productFormIns.Qty = item.Qty;
                    productFormIns.Price = item.Price;

                    db.ProductFormIn.Add(productFormIns);
                }
           
                db.SaveChanges();
            }
            else if (a == "2") // out
            {
                foreach (var item in products)
                {
                    var checkstock = (from t1 in db.Product
                                      where t1.Productid == item.Productid
                                      select t1).SingleOrDefault();
                    if (checkstock.Qty < item.Qty)
                    {

                        ModelState.AddModelError(string.Empty, "'"+checkstock.Productname+"' ของใน Stock มีไม่พอ");
                        proid = products.Select(c => c.Productid).ToList();
                        OnGet(proid);
                        return Page();
                        //return RedirectToPage("./Product"); // ของมีไม่ถึง
                    }
                }

                int id = 0;
                FormOut formOut = new FormOut();

                formOut.Userid = userid;
                //formIn.Status = false;
                formOut.Createdate = DateTime.Now;

                db.FormOut.Add(formOut);
                db.SaveChanges();
                id = formOut.FormOutid;

                foreach (var item in products)
                {
                    ProductFormOut productFormOut = new ProductFormOut();

                    productFormOut.FormOutid = id;
                    productFormOut.ProductId = item.Productid;
                    productFormOut.Qty = item.Qty;
                    productFormOut.Price = item.Price;

                    db.ProductFormOut.Add(productFormOut);
                }
                db.SaveChanges();
            }
            return RedirectToPage("./Product");
        }

        [BindProperty]
        public List<int> proid { get; set; }

        [BindProperty]
        public string formId { get; set; }

        [BindProperty]
        public List<Product> products { get; set; } = new List<Product>();
    }
}

StockVinul/stockproject/Pages/Stock/CreateProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;

namespace stockproject
{
    public class CreateProductModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();

        private IHostingEnvironment _environment;
        public CreateProductModel(IHostingEnvironment environment)
        {
            _environment = environment;
        }
        public ActionResult OnGet(string _name, string _description, string _price, float _discount)
        {
            name = _name;
            description = _description;
            price = _price;
            discount = _discount;
            return Page();
        }
        public ActionResult OnPostToCreateAsync()
        {
            var userid = Convert.ToInt32(User.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault());
            if (name == null || price == null)
            {
                return Page();
            }

            var a = name;
            var a1 = price;
            // ถ้า ไม่มีการอัพโหลดภาพเข้าระบบ จะให้แสดงข้อความแจ้งเตือนที่หน้าจอ และให้ทำรายการใหม่
            if (Upload == null)
            {
                //ModelState.AddModelError(string.Empty, "กรุณาเพิ่มรูปภาพสินค้า");
                OnGet(name, description, price, discount);
                return Page();
            }
            string newfileName = DateTime.Now.Ticks.ToString() + "_" + Upload.FileName;
            var path = Path.Combine(_environment.WebRootPath, "Pic", newfileName);

            Product table = new Product();
            table.Productname = name;
            table.Qty = 0;
            table.Price = Int32.Parse(price);
            table.Userid = userid;
            table.Picpath = newfileName;
            table.Modifydate = DateTime.Now;
            table.Description = description;
            table.Discount = discount;

            FileStream stream = new FileStream(path, FileMode.Create);
            Upload.CopyToAsync(stream);

            db.Product.Add(table);
            db.SaveChanges();

            return RedirectToPage("./Product", "OnGet");
        }



        //public void OnPostTest()
        //{

        //}
        [Required(ErrorMessage = "กรุณาเพิ่มรูปภาพสินค้า")]
        [BindProperty]
        public IFormFile Upload { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "กรุณาใส่ชื่อสินค้า")]
        public string name { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "กรุณาใส่ราคาสินค้า")]
        public string price { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "กรุณาใส่คำอธิบายสินค้า")]
        public string description { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "กรุณาใส่ส่วนลด หากไม่มีกรุณากรอก 0")]
        public float discount { get; set; }
    }
}

StockVinul/stockproject/Pages/Stock/Product.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;

namespace stockproject.Pages.Stock
{
    public class ProductModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();
        public List<Product> list { get; set; } = new List<Product>();
        [BindProperty]
        public List<int> prid { get; set; }
        [BindProperty]
        public bool? viewMode { get; set; } = true;

        public ActionResult OnGet(bool mode)
        {
            viewMode = mode;
            list = (from t1 in db.Product
                    select t1).ToList();

            return Page();
        }
        public ActionResult OnPostToCreate()
        {
            if (prid != null || prid.Count != 0)
            {
                return RedirectToPage("./CreateForm", "OnGet", new { proid = prid });
            }
            else
            {
                return Page();
            }
        }
        public ActionResult OnPostToCreateProduct()
        {
            return RedirectToPage("/Stock/CreateProduct");
        }
        public ActionResult OnPostToUpdateProduct(List<Product> list)
        {
            foreach (var item in list)
            {
                //Product product = new Product();
                var listp = (from t1 in db.Product
                             where t1.Productid == item.Productid
                             select t1).SingleOrDefault();


                listp.Productname = item.Productname;
                listp.Description = item.Description;
                listp.Discount = item.Discount;
                listp.Price = item.Price;
                listp.Modifydate = DateTime.Now;
            }
            db.SaveChanges();

            //return OnGet(false);
            return RedirectToPage("./Product", "OnGet", new { mode = false });
        }

        public ActionResult OnPostChangeView()
        {
            //var a = viewMode.Value;
            //viewMode = null;
            //ModelState.Clear();

            //viewMode = a;
            return RedirectToPage("/Stock/Product", "OnGet", new { mode = !viewMode });
        }
    }
}

StockVinul/stockproject/Pages/Stock/CreateForm.cshtml
@page
@model stockproject.Pages.Stock.CreateFormModel
@{
    ViewData["Title"] = "CreateForm";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@if (Model.products.Count == 0)
{
    <div class="row">
        <div class="col-12 text-center">
            <span class="mr-2">กรุณาเลือกสินค้าก่อนทำรายการต่อไป.</span>
        </div>
    </div>
}
else
{
    <form method="post">
        <div class="row mt-5 mb-3">
            <div class="col-12 text-center">
                <h3>เพิ่มรายการเคลื่อนย้าย</h3>
            </div>
        </div>
        <div class="container-create-form">
            <div class="wrap-create-form">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <lable>ประเภทรายการ: </lable>
                            @Html.DropDownListFor(model => model.formId,
                                new List<SelectListItem> {
                               new SelectListItem { Value = "1" , Text = "ใบนำเข้า" },
                               new SelectListItem { Value = "2" , Text = "ใบนำออก" },
                               }, new { @class = "form-control my-select-box-custom", @type = "text" })
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-12">
                        <div class="table-wrapper">
                            <table class="table table-hover my-table-custom">
                                <thead class="text-center">
                                    <tr>
                                        <th>#</th>
                                        <th></th>
                                        <th>สินค้า</th>
                                        <th>จำนวน <small>(หน่วย)</small></th>
                                        <th>ราคา/หน่วย <small>(บาท)</small></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (int i = 0; i < Model.products.Count; i++)
                                    {
                                        <tr>
                                            <td>@(i + 1)</td>
                                            <td>
                                                <span>
                                                    <img class="img-table-view" src="~/pic/@Model.products[i].Picpath" width="277" height="180">
                                                </span>
                                            </td>
                                            <td>@Model.products[i].Productname</td>
                                            <td style="width: 200px;">
                                                @Html.TextBoxFor(value => value.products[i].Qty, new { @type = "number", @placeholder = "0", @class = "form-control my-text-input-custom", @required = true, @min = "1" })
                                                @Html.HiddenFor(value => value.products[i].Productid)
                                                @Html.HiddenFor(value => value.products[i].Price)
                                            <td class="text-right pr-4">@Model.products[i].Price</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-12">
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-12 text-right">
                        <button class="btn btn-primary" asp-page-handler="Create"><i class="fas fa-check mr-2"></i>สร้างรายการ</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

}

StockVinul/stockproject/Pages/Stock/Product.cshtml
@page
@model stockproject.Pages.Stock.ProductModel

@{
    ViewData["Title"] = "Product";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<form method="post">
    <div class="row mt-5 mb-3">
        <div class="col-12 text-center">
            <h3>คลังสินค้า</h3>
        </div>
        <div class="col-6 text-left">
            @Html.HiddenFor(model => model.viewMode)
            @if (@Model.viewMode == true)
            {
                <button asp-page-handler="ChangeView" class="btn btn-primary"><i class="far fa-images"></i></button>
            }
            else
            {
                <button asp-page-handler="ChangeView" class="btn btn-primary"><i class="fas fa-table"></i></button>
            }
        </div>
        <div class="col-6 text-right">
            <button asp-page-handler="ToCreate" class="btn btn-primary"><i class="fas fa-file-medical mr-2"></i>สร้าง</button>
            <button asp-page-handler="ToCreateProduct" class="btn btn-primary"><i class="fas fa-cubes mr-2"></i>เพิ่มสินค้า</button>
            @{
                @using System.Security.Claims;
                var role = User.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).SingleOrDefault();
                if (role == "1")
                {
                    @if (@Model.viewMode == true)
                    {
                        <button asp-page-handler="ToUpdateProduct" class="btn btn-primary"><i class="fas fa-cubes mr-2"></i>แก้ไขสินค้า</button>
                    }
                }
            }
        </div>
    </div>
    @if (@Model.viewMode == true)
    {
        <div class="container-table100 text-center">
            <div class="wrap-table100">
                <table class="table table-hover my-table-custom">
                    <thead>
                        <tr>
                            <th style='text-align:center;'>#</th>
                            <th style='text-align:center;'>เลือก</th>
                            <th style='text-align:center;'></th>
                            <th style='text-align:center;'>สินค้า</th>
                            <th style='text-align:center;'>คำอธิบาย</th>
                            <th style='text-align:center;'>คงเหลือ  <small>(หน่วย)</small></th>
                            <th style='text-align:center;'>ราคา<small>/หน่วย</small> <small>(บาท)</small></th>
                            <th style='text-align:center;'>ส่วนลด</th>
                        </tr>
                    </thead>

                    <tbody style="height: 250px; overflow-y: auto; overflow-x: hidden;">
                        @if (Model.list.Count == 0)
                        {
                            <tr class="text-center">
                                <td colspan="8">
                                    ไม่พบข้อมูลสินค้าในระบบ
                                </td>
                            </tr>
                        }
                        else
                        {
                            @for (int i = 0; i < Model.list.Count; i++)
                            {

                                <tr>
                                    <td style='text-align:center;'>
                                        @(i + 1)
                                    </td>
                                    <td>
                                        <label class="checkbox-container">
                                            <input class="form-check" name="prid" type="checkbox" value="@Model.list[i].Productid" />
                                            <span class="checkmark" style="top: -2vh; left: 2vw;"></span>
                                        </label>
                                    </td>
                                    <td>
                                        <span>
                                            <img class="img-table-view" src="~/pic/@Model.list[i].Picpath" width="277" height="180">
                                        </span>
                                    </td>
                                    @if (role == "1")
                                    {
                                        <td style='text-align:center;'>@Html.TextBoxFor(m => m.list[i].Productname, new { @class = "form-control my-text-input-custom", @type = "text" })</td>
                                        @Html.HiddenFor(m => m.list[i].Productid)

                                        <td style='text-align:center;'>@Html.TextBoxFor(m => m.list[i].Description, new { @class = "form-control my-text-input-custom", @type = "text" })</td>
                                        <td style='text-align:center;'>@Model.list[i].Qty</td>

                                        <td style='text-align:center;'>@Html.TextBoxFor(m => m.list[i].Price, new { @class = "form-control my-text-input-custom", @type = "number" })</td>
                                        <td style='text-align:center;'>@Html.TextBoxFor(m => m.list[i].Discount, new { @class = "form-control my-text-input-custom", @type = "text" })</td>
                                    }
                                    else
                                    {
                                        <td style='text-align:center;'>@Model.list[i].Productname</td>

                                        <td style='text-align:center;'>@Model.list[i].Description</td>
                                        <td style='text-align:center;'>@Model.list[i].Qty</td>

                                        <td style='text-align:center;'>@Model.list[i].Price</td>
                                        <td style='text-align:center;'>@Model.list[i].Discount</td>

                                    }

                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
    else
    {
        <div class="row product-card-list">
            @if (Model.list.Count == 0)
            {
                <table class="table table-hover my-table-custom">
                    <tbody>
                        <tr class="text-center">
                            <td colspan="8">
                                ไม่พบข้อมูลสินค้าในระบบ
                            </td>
                        </tr>
                    </tbody>
                </table>
            }
            else
            {
                @for (int i = 0; i < Model.list.Count; i++)
                {
                    <div class="col-lg-3 col-md-4 col-sm-12 col-xl-3 mb-3 mt-3">
                        <div class="card">
                            <div class="card-header">
                                <span class="img-card-view"><img src="~/pic/@Model.list[i].Picpath" width="277" height="180"></span>
                            </div>
                            <div class="card-title">
                                <div class="row">
                                    <div class="col-2">
                                        <label class="checkbox-container">
                                            <input class="form-check" name="prid" type="checkbox" value="@Model.list[i].Productid" />
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="col">
                                        <span>@Model.list[i].Productname</span>
                                    </div>
                                </div>
                                <br />
                                <span style="margin-left: 35px;" class="text-muted">
                                    @Model.list[i].Description
                                </span>
                            </div>
                            <hr class="mt-0" />
                            <div class="card-body pt-0">
                                <div class="row">
                                    <div class="col-12 text-right">
                                        <span class="qty">
                                            คงเหลือ: @Model.list[i].Qty <small>หน่วย</small>
                                        </span>
                                    </div>
                                    @*<div class="col-12 text-right">
                                            <span class="description">
                                              คำอธิบาย:
                                            </span>
                                        </div>*@
                                    <div class="col-12 text-right">
                                        <span class="price">
                                            ราคา<small>/หน่วย</small>: @Model.list[i].Price <small>บาท</small>
                                        </span>
                                    </div>
                                    <div class="col-12 text-right">
                                        <span class="discount">
                                            ส่วนลด : @Model.list[i].Discount <small>%</small>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    }
</form>